ericmjl/pyjanitor

janitor/functions.py, tests/test_functions.py
Change `cleaan_names` so that it works for MultiIndexes and also add tests for this.
Fixes #10
=> Clean names multiindex

janitor/functions.py, tests/test_functions.py
Adds kwarg to the function `clean_names` to strip leading and trailing underscores.
I did change some the syntax previously decided in the original issue. This was because I used pythons built-in `strip`, `lstrip` and `rstrip` string functions to remove the underscores. Therefore, it seemed more intuitive and "pythonic" to use `'left'` and `'right'` (and `'both'`).
I also added a shorthand `'l'` and `'r'` and `True`. This type of behaviour is common place in the Pandas API e.g. [here](https://github.com/pandas-dev/pandas/blob/v0.22.0/pandas/core/generic.py#L5319) and [here](https://github.com/pandas-dev/pandas/blob/a00154dcfe5057cb3fd86653172e74b6893e337d/pandas/io/parsers.py#L172), so this should be familiar to users.
We can also add `'end'` and `'start'` easily if these are still …
=> Clean names remove outer underscores

janitor/functions.py
I tried to run `pyjanitor` on my system and got the following error:
```
/Users/claire/anaconda/lib/python2.7/site-packages/pyjanitor-0.1.1-py2.7.egg/janitor/functions.pyc in <lambda>(x)
74                            .replace(':', '_')
75                            .replace("'", '')
---> 76                            .replace('’', '')
77                            .replace(',', '_')
78                            .replace('?', '_')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```
I've gotten this before because of the funny single apostrophe, so was able to fix it by explicitly declaring utf-8 encoding. I'm using Python 2.7, so perhaps this isn't a problem in Python 3?
Also a side note that this edit fixes the error and passes the …
=> Fix unicode error from single apostrophe

.bumpversion.cfg, .readthedocs.yml, README.rst, janitor/__init__.py, janitor/functions.py, setup.py, tests/test_df_registration.py
Enables new way of using pandas dataframes: just import janitor, and all of janitor's functions are automatically attached and registered onto a pandas DataFrame object! No more wrapping :smile:
=> Rework pandas flavour

AUTHORS.rst, janitor/functions.py, tests/test_functions.py
As per [issue 15](https://github.com/ericmjl/pyjanitor/issues/15) I've added a limit_column_characters function.
There's three tests; they should be sufficient.
I don't think we could have gone with the suggestion to use the df_column_uniquify function in [this stackoverflow answer](https://stackoverflow.com/a/44957247) since it will only work if the duplicate columns are next to each other. If they skip and repeat later, the count starts again.
=> Add limit_column_characters function with tests

docs/round_to_fraction.rst, examples/round_to_fraction.md, janitor/functions.py, tests/test_functions.py
I added a `round_to_fraction` which rounds floats in a column to the nearest fraction.
I.e. you can round to the nearest half, third or 1/7th.
I saw it as a feature request for R's janitor: https://github.com/sfirke/janitor/issues/235
=> Add round_to_fraction with tests and example

janitor/functions.py, tests/test_functions.py
I added a few parameters to the clean_names method. Namely:
1. I added a `remove_special` parameter that removes all special characters and only retains letters, numbers and underscores.
2. I changed `preserve_case` to `case_type`. This way I was able to add an 'upper' option (I like uppercase column names). This also allows it to be more extensible in the future if you want to add camelCase, Title_Case, etc.
These should close out Issue #15, except that there still isn't an option to choose the character spaces should be changed to. I think they should always be underscores, though, and the current default is fine.
=> Added remove_special and case_type to clean names

janitor/functions.py
UserWarning: Pandas doesn't allow columns to be created via a new attribute name
This PR resolves issue #68 
- docs build
- 
- 
- 
- @ericmjl
=> Suppress user warning

janitor/functions.py
Old docstring name for `transform_column` remained after function name was apparently changed.
@ericmjl
=> changed transform to transform_column in docstring to match func name

.travis.yml
Follows policy of supporting last two versions of Python.
=> Remove Py35 from Travis build matrix

janitor/functions.py, tests/functions/test_convert_unix_date.py, tests/test_df_registration.py
- docs build
Added a method to convert Unix epoch time to python `datetime` objects.
I understand that this is quite trivial and if you don't believe it is worth
adding it to `pyjanitor` feel free to close it.
Please tag maintainers to …
=> convert unix epoch time

environment-dev.yml
https://github.com/ericmjl/pyjanitor/issues/126
Just went ahead and did this because it was so trivial; not trying to bypass discussion.
@ericmjl @szuckerman
=> update py3 dep to require 3.6 or later rather than specifically 3.6

environment-dev.yml
This PR resolves `environment-dev.yml` issues (not previously posted):
- JupyterLab should be a development dependency given we have example notebooks
- Python 3.6 was specifically getting pinned again (unintentional?)
- Known problem when RDKit is used on a system without X libraries being present:
https://sourceforge.net/p/rdkit/mailman/message/36341795/
This is relevant for people using Windows Subsystem for Linux.
> Hi,
>
>This looks like an error caused by the fact that the anaconda cairo builds
include a dependency on the system X libraries and you don't have X
installed.
>You can probably clear the problem up by installing the cairo build from
the RDKit channel. Run this inside the conda environment where you have the
RDKit installed:
>
>conda install -c rdkit nox
>conda install -c …
=> Fix environment-dev.yml

tests/chemistry/test_maccs_keys_fingerprint.py, tests/chemistry/test_molecular_descriptors.py, tests/chemistry/test_morgan_fingerprint.py, tests/chemistry/test_smiles2mol.py
This PR resolves #193.
- Adds a `skipif` around tests that you want to be optional
If you have a preferred logic for skipping, I'm happy to modify. I've also paraphrased the reason from what @ericmjl was saying.
- @ericmjl
=> Add skipif for tests you don't want locally

janitor/functions.py, tests/functions/test_expand_column.py
This PR resolves #59. 
- Updates argument `column` to `column_name`
- Updates variable `expanded` to `expanded_df`
- Accommodates backwards compatibility by accepting old argument `column`
- @ericmjl
=> Fix naming conventions in expand_column()

janitor/functions.py, tests/functions/test_remove_empty.py
Added a test to check index after remove_empty ; added a reset_index in remove_empty to fix the test
This PR resolves #213 .
- docs build
- 
- 
- 
- @ericmjl
=> Added a test to identify index issue + Fixed index post remove_empty() 

tests/functions/test_convert_unix_date.py
This PR resolves #256 
- docs build
- Added in a `pytest.mark` to the Unix time check function to check for a Windows OS, per this [Stack Overflow article](https://stackoverflow.com/questions/1325581/how-do-i-check-if-im-running-on-windows-in-python)
Please tag maintainers to …
=> [TST] Add test skip for checking Unix time on Windows

janitor/utils.py, tests/utils/test_deprecated_alias.py
This PR addresses #59. 
- docs build
- Added decorator to use when deprecating old function arguments
- @ericmjl
=> [ENH] Add decorator to cleanly alias deprecated arguments

janitor/functions.py, janitor/io.py, tests/functions/test_groupby_agg.py, tests/functions/test_label_encode.py, tests/functions/test_read_csvs.py
Addresses Issue #59 
- Applied new alias decorator #305 to functions with previously updated argument names
- `isort` picked up some imports to reorder in some other files
**This PR addresses #59.**
If you are adding code changes, please ensure the …
=> [ENH] Apply new alias decorator to previously updated functions

.readthedocs.yml
- Populated the YAML file with build instructions for readthedocs.
- In particular, ensured `requirements.txt` and `requirements-dev.txt` were both used to install packages.
**This PR resolves #222.**
=> [DOC] Use readthedocs YAML v2 for building docs

tests/biology/test_join_fasta.py
Closes #330 
Test locally more easily by only removing the single `biopython` package with: `conda remove --force biopython`. You'll see the `skipif` message show up.
- @ericmjl
=> [TST] add skipif for biology

CONTRIBUTING.rst, LICENSE, README.rst
=> [DOC] various doc changes incl contributing

janitor/functions.py
Refactors `clean_names` in functions to simplify by using the `re` module. This makes it easier to add more sophisticated column name normalizations later.
**This PR resolves #203 .**
The docs build part of `make check` is failing, so I ran `make docs` individually as listed in the Makefile but I am still getting the messages including:
- build succeeded, 15 warnings
- The message includes "WARNING: document isn't included in any toctree"
Please note that my code changes do not change the behavior and all tests pass.
@ericmjl please advise.
=> [ENH] Refactor clean_names in functions

.azure-pipelines/pipeline-master.yml
- I have removed py36 from the build matrix. This should reduce the number of slots used per PR for CI builds, and hence speed up the time taken when there are multiple builds taking place.
=> [INF] Test only on latest Python version

janitor/functions.py, janitor/utils.py, requirements-dev.txt, tests/biology/test_join_fasta.py, tests/functions/test_bin_numeric.py, tests/functions/test_groupby_agg.py, tests/functions/test_impute.py
- Fix f-string for argument deprecation warning (!!)
- Updated deprecated arguments in tests
- Add type hints to some function returns
- docs build
Please tag …
=> [DOC] Fix deprecation warning, deprecations and type hints

AUTHORS.rst, CONTRIBUTING.rst
I would like to propose a change, such that now this documentation has less typographic and grammar errors. The fixes are:
- "You can contribute in many ways" >> "The following sections detail a variety of ways to contribute, as well as how to get started."
- "official pyjanitor docs, in docstrings, the examples gallery." >> "official pyjanitor docs, in docstrings, or the examples gallery."
- "Doing so has manyfold benefits:" >> "Doing so has numerous benefits:"
- "Every newcomer is equal in our eyes, and it's the most egalitarian way to get started, regardless of experience." >> "Every newcomer is equal in our eyes, and it's the most egalitarian way to get started (regardless of experience)."
- Remove comma after "Remote contributors outside of sprints,"
- Convert all (3) uses of "PR" to …
=> [DOC] CONTRIBUTING.rst: Fix typos and errors, add hyperlinks

AUTHORS.rst, examples/notebooks/medium_franchise.ipynb, janitor/functions.py, tests/functions/test_deconcatenate_column.py, tests/functions/test_deconcatenate_column_preserve_position.py
This PR adds a boolean kwarg `preserve_position` to pyjanitor function `deconcatenate_column`. The default is set to `False` to avoid introducing breaking changes.
When `preserve_position=True`
`df.columns` change from `[... id ...]` into `[... col1, col2, ...]`
When `preserve_position=False` (default)
`df.columns` change from `[... id ...]` into `[... id ... col1, col2]`
**This PR resolves #478.**
- running the test …
=> [ENH] add preserve_position kwarg to deconcatenate_column #478

AUTHORS.rst, CONTRIBUTING.rst, README.rst, pyproject.toml, setup.py
- Documentation for users and contributors explicitly state Python 3.6+ compatibility
- `black` is configured to support python 3.6 & 3.7
- `setup.py` requires Python 3.6+
**This PR resolves #493.**
- docs build
If `make check` does not work for you, you can execute the commands listed …
=> [DOC] Clarify Python version compatibility to >=py36

.github/pull_request_template.md
=> [DOC] Update PR template to include changelog in release.

CONTRIBUTING.rst
This PR contains the following additions to `CONTRIBUTING.rst`:
-  Guidelines and examples for docstring style
-  Guidelines and examples for code patterns
-  Guidelines and examples for example-based unit tests
**This PR resolves #488.**
**Sorry, but I don't see the `CHANGELOG.rst` file. Where is it?**
To …
=> [DOC] Docstring n code guideline #488

AUTHORS.rst, CHANGELOG.rst, janitor/functions.py, tests/functions/test_clean_names.py
Changes proposed in the pull request: 
- add optional removal of accents on functions.clean_names, enabled by default.
Example API:
``` python
df = pd.DataFrame({"João": [1, 2], "Лука́ся": [1, 2], "Käfer": [1, 2]})
df = df.clean_names(strip_accents=True)
expected_columns = ["joao", "лукася", "kafer"]
assert set(df.columns) == set(expected_columns)
```
This PR resolves #502 
- Do use some discretion here; if …
=> [ENH] Add optional removal of accents on functions.clean_names, enabled by default.

CHANGELOG.rst, janitor/functions.py, tests/functions/test_clean_names.py
- Adds the option to convert names to snake_case from camelCase.
- Adds a bunch of tests relevant to the problem.
- References the original implementation on GitHub Gists.
**This PR resolves #498.**
- @hectormz 
- @szuckerman 
- @sallyhong 
- @zbarry 
- @jk3587
=> [ENH] Add snake option to clean_names

CHANGELOG.rst, README.rst, setup.py
- Copy relevant sections from `README.rst` for PyPI project description
**This PR resolves #495.**
- …
=> [DOC] Add PyPI description

CHANGELOG.rst, examples/notebooks/inflating_converting_currency.ipynb
- Added an example notebook for the `convert_currency()` and `inflate_currency()` methods in the finance submodule (uses USDA expenditure data).
**This PR resolves #503.**
(Already on the authors list)
- …
=> [ENH] Add Example Notebook for Finance Submodule

AUTHORS.rst, CHANGELOG.rst, janitor/functions.py, janitor/utils.py, pytest.ini, tests/functions/test_flag_nulls.py, tests/utils/test_check_column.py
Adds a null flag function, which creates a new column in a DataFrame to mark which rows had null values. You can choose a subset of columns to consider as needed.
**This PR resolves #501.**
- docs build
If `make …
=> [ENH] Add null_flag function #501

examples/notebooks/teacher_pupil.ipynb
- Fixes #476 
- Move down the header `Data Dictionary` down one level
**This PR resolves #476.**
- …
=> [DOC] Fix markdown level for intl teach notebook #476

AUTHORS.rst, CHANGELOG.rst, janitor/utils.py, tests/utils/test_skiperror.py, tests/utils/test_skipna.py
- Implements the functions proposed in #549 
- Provides decorators `.utils.skipna` and `.utils.skiperror` for skipping np.nan and errors
**This PR resolves #549 **
1. [x ] PR in from a fork off your branch. Do not PR from `<your_username>`:master, but rather from `<your_username>`:<branch_name>.
- @ericmjl
=> [ENH] Add decorators to skip nans and errors in iteration

CHANGELOG.rst, janitor/chemistry.py
This PR closes #558.
Changes made:
* We added `useChirality=True`.
* We do not surface this as an option to end-users because this should be on by default.
=> [ENH] Change morgan_fingerprints to use chirality by default

CHANGELOG.rst, janitor/functions.py, tests/functions/test_deconcatenate_column.py, tests/utils/test_skiperror.py, tests/utils/test_skipna.py
- `deconcatenate_column` now contains logic to handle splitting collections like tuples / lists on top of splitting strings
**This PR resolves *nothing*.**
- …
=> [ENH] Add functionality to deconcatenate tuple/list/collections in a column to deconcatenate_column

AUTHORS.rst, CHANGELOG.rst, janitor/functions.py
Now it actually prints the length you need to provide instead of the length that was wrongly provided
**This PR resolves #541 .**
- docs build
- @ericmjl
=> [ENH] Fix error message when length of new_column_names is wrong

CHANGELOG.rst, CONTRIBUTING.rst
- New codeblock on installing `pre-commit` isn't formatted correctly.
**This PR resolves #603 .**
- docs build
- @ericmjl
(I guess I didn't review closely enough!)
=> [DOC] Fix command formatting in CONTRIBUTING.rst

CHANGELOG.rst, janitor/functions.py, tests/functions/test_clean_names.py
- Enforces string type for column names when calling `clean_names()`.
- Coercion is on by default; can be turned off by a flag.
- Docstring documents the behaviour of the function.
**This PR resolves #612.** 
Happy to take comments from anybody tagged here :smile::
- @rahosbach 
- @zbarry 
- @szuckerman 
- @jk3587 
- @sallyhong 
- @shandou 
- @hectormz
=> [ENH] Enforced string column names by default when using clean_names.

CHANGELOG.rst, examples/notebooks/bad_values.ipynb, janitor/functions.py, tests/functions/test_find_replace.py
This PR now lets us `find_replace` using the following pattern:
```python
df = pd.DataFrame(...)
df = df.find_replace(column1={"hello": "world"}, column2={"what's up": "world"})
```
I have left out `find_replace_all`, because `df.replace()` natively fulfills this functionality.
This PR closes #255.
h/t @nickdelgrosso for the API change suggestion!
=> [ENH] Implement find_replace API change

CHANGELOG.rst, tests/biology/test_join_fasta.py, tests/chemistry/test_maccs_keys_fingerprint.py, tests/chemistry/test_molecular_descriptors.py, tests/chemistry/test_morgan_fingerprint.py, tests/chemistry/test_smiles2mol.py, tests/ml/test_get_features_targets.py
- Adds docstrings to tests in following modules:
- `ml`
- `biology`
- `chemistry`
I did not write any of the original functions or tests, and am open to feedback for better descriptions.
**This PR partially addresses #306.**
To do a very …
=> [TST] Add test docstrings to ml, biology, chemistry modules

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/noop.txt, .travis.yml, scripts/docker_deploy.sh
The purpose of this PR is to provide a development container that new users can opt in to use.
I have made the following choices:
1. We build the conda environment in the container on Travis, repeatedly and automatically. This way, nobody should need to build it locally.
1. Users can then pull the Docker container and develop code from within it.
This is all intended to work with VSCode Remote (Container) extension: https://code.visualstudio.com/docs/remote/containers
=> [INF] First attempt at a dev container

CHANGELOG.rst, janitor/functions.py, tests/functions/test_update_where.py
- Changed update_where conditions to query style mode
- Removed find_replace dependency on update_where function
-
**This PR resolves #663 .** …
=> [ENH] updates to update_where and find_replace functions

.azure-pipelines/pipeline-master.yml, CHANGELOG.rst, tests/biology/test_join_fasta.py, tests/chemistry/test_maccs_keys_fingerprint.py, tests/chemistry/test_molecular_descriptors.py, tests/chemistry/test_morgan_fingerprint.py, tests/chemistry/test_smiles2mol.py, tests/helpers.py, tests/spark/conftest.py, tests/spark/functions/test_clean_names_spark.py, tests/spark/functions/test_update_where_spark.py, tests/test_helpers.py
- Ensure that optional tests (for optionally installed packages) can be skipped on local machines (**but not CI**)
- Adds custom `importorskip` (borrowed from https://github.com/arviz-devs/arviz/pull/1113) to prevent skips on CI machine
- Removes `pytest.mark.skipif` wrapper on pyspark fixtures, which seems to be not needed (?)
**This PR resolves #115.**
3. [X] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the …
=> [TST] Only skip tests for non-installed packages on local machine
