janitor/functions.py
tests/test_functions.py

Added preserve_case to the clean_names function and documented in function docstring. Added test to check for preserve_case=True.
Closes #17 if accepted :)

Add clean names preserve case

---

CONTRIBUTING.rst
docs/example.rst

Updated example to use new non-dataframe API.

Example rework

---

janitor/functions.py
tests/test_df_registration.py
tests/test_functions.py

This makes changing of datatypes and removing columns compatible with the method chaining paradigm.

Added change_type and remove_column

---

.gitignore
AUTHORS.rst
README.rst
janitor/functions.py

Addresses #35.
py.test successful. flake8 warned about a couple different unused imports / vars in tests/.

Documentation fixes on outdated function names and related

---

.gitignore
janitor/functions.py

Added custom function for type checking. Makes checking types less verbose inline in the code base.

Type checking fix

---

janitor/functions.py
tests/test_functions.py

New feature: add_columns

---

Makefile
environment-dev.yml
janitor/functions.py
pyproject.toml
tests/test_df_registration.py
tests/test_functions.py

- Adds a transform function
- Applied Black formatting to codebase.
- @ericmjl

Added transform function

---

janitor/functions.py
tests/test_functions.py

63 add column str fix

---

README.rst

Selfishly and shamelessly making pandas_flavor a link in pyjanitor's README 😉

make pandas_flavor a link in README

---

janitor/functions.py
tests/test_functions.py

This PR resolves #74 and my boredom on a Saturday.
- docs build
- Gives user ability to store result of a column transformation in a new destination column
- @ericmjl

74-transform-column-enhancement

---

janitor/functions.py
tests/test_functions.py

This PR resolves #61 
- docs build
- Addresses #61 
- @ericmjl

61-collapse-levels

---

janitor/functions.py
tests/test_functions.py

This PR resolves #48 .
- docs build
reset_index_inplace
- @ericmjl

48-reset_index_inplace

---

janitor/functions.py

- docs build
- Because the implementation of filter_on has changed, I have updated the docstring to reflect this.
- @ericmjl
- @szuckerman 
- @zbarry

filter_on docfix

---

requirements.txt

This PR resolves #91.
- Removes scipy as a dependency. It is probably a legacy thing. 
- @ericmjl

Remove scipy dependency

---

README.rst

- docs build
Adds in a few lines describing pyjanitor's features. Long-overdue!
- @ericmjl
- @szuckerman 
- @zbarry

Updated description of pyjanitor features

---

Makefile
environment-dev.yml
janitor/biology.py
janitor/chemistry.py
janitor/functions.py
janitor/utils.py
tests/test_functions.py

This PR resolves #97 .
- docs build
- import sorting
- implements try/except for imports that are inside the submodules.
- @ericmjl

Raise import errors if submodules are not found

---

docs/api.rst
janitor/biology.py
janitor/chemistry.py
janitor/finance.py
janitor/functions.py

Brings documentation up-to-date with submodules and appropriately worded module docstrings.

Documentation omnibus update

---

janitor/functions.py
tests/test_df_registration.py
tests/test_functions.py

- docs build
Add a Matlab date converter akin to the the Excel date converter.
- @ericmjl :wink:

Convert malab date

---

janitor/functions.py
tests/test_functions.py

Added select_columns function with an option to invert columns that will alternatively drop selected columns.
This PR resolves #77 .
- docs build
- 
- 
- 
- @ericmjl

Update functions.py with select_columns function

---

janitor/functions.py
tests/functions/test_add_column.py
tests/functions/test_remove_empty.py
tests/functions/test_reorder_columns.py

As per title. Does not resolve any issue.

updated add_column tests to use hypothesis

---

CONTRIBUTING.rst

Added documentation on how to write tests, fixed rst formatting

---

CONTRIBUTING.rst

First draft addressing proposal in #118. 
@ericmjl @szuckerman

updated contributing w.r.t. a proposal to introduce a dev-master merge split

---

examples/then.md
janitor/functions.py
tests/functions/test_then.py

This PR resolves #130 
- docs build
- This allows people to add arbitrary functions to the method chain.
- @ericmjl
- @zbarry

Add then function

---

janitor/functions.py
tests/conftest.py
tests/functions/test_dropnotnull.py

This PR resolves #132.
- docs build
- Adds a `dropnotnull` function.
- @ericmjl
- @zbarry 
- @szuckerman

added dropnotnull function

---

AUTHORS.rst
janitor/functions.py
tests/functions/test_select_columns.py

This PR resolves #(https://github.com/ericmjl/pyjanitor/issues/77).
- docs build
-  Add the functionality of selecting columns based on a shell-style glob string (e.g., `*_thing_*`)
-  Enable users to manually …

Update select columns

---

janitor/chemistry.py
tests/test_chemistry.py

- docs build
- In this PR, I have generalized the morganbits function to also include morgan counts. 
- @ericmjl

Morgan counts

---

AUTHORS.rst
README.rst
janitor/chemistry.py
janitor/functions.py
tests/conftest.py
tests/functions/test_dropnotnull.py
tests/functions/test_select_columns.py
tests/test_chemistry.py

Rolling PR for 0.16.5. Any new merges into `dev` will automatically be reflected here.
WIP in title ensures we're always reminded that this is not ready to go until we're ready to cut a new release!

Rolling PR for 0.16.5

---

.bumpversion.cfg
janitor/__init__.py
setup.py

- docs build
- 
- 
- 
- @ericmjl

Sync up dev with master

---

Makefile
janitor/functions.py
tests/functions/test_transform_columns.py

This PR introduces a plural function for `transform_column`.

Transform columns

---

janitor/functions.py
tests/functions/test_find_replace.py

This PR resolves #93. Been having this idea for a while. Finally got down to an implementation that I have repeatedly re-invented for myself at work, so I thought it'd be best to put this into pyjanitor.
- docs build
Please describe the changes proposed in the pull …

added find_replace function

---

janitor/biology.py
janitor/chemistry.py
janitor/finance.py
janitor/functions.py
janitor/testing_utils/strategies.py
tests/functions/test_add_column.py
tests/functions/test_add_columns.py
tests/functions/test_clean_names.py
tests/functions/test_encode_categorical.py
tests/functions/test_filter_column_isin.py
tests/functions/test_get_features_targets.py
tests/functions/test_remove_empty.py
tests/functions/test_rename_column.py
tests/functions/test_reorder_columns.py

Simply a linting fix, nothing else.

python linting fixes

---

janitor/biology.py
janitor/chemistry.py
janitor/finance.py
janitor/functions.py
janitor/testing_utils/strategies.py
tests/finance/test_convert_currency.py
tests/functions/test_add_column.py
tests/functions/test_add_columns.py
tests/functions/test_clean_names.py
tests/functions/test_encode_categorical.py
tests/functions/test_filter_column_isin.py
tests/functions/test_get_features_targets.py
tests/functions/test_remove_empty.py
tests/functions/test_rename_column.py
tests/functions/test_reorder_columns.py

This PR resolves #147. 
- docs build
- Marks the finance test as xfail, so that this does not cause the test suite to fail even if the API call fails.
- @ericmjl

xfail finance test and applied black

---

.azure-pipelines/pipeline-master.yml
.azure-pipelines/templates/create-env.yml
.azure-pipelines/templates/run-tests.yml
azure-pipelines.yml

This is a PR to move pyjanitor off Travis and onto Azure Pipelines.

Azure pipelines

---

AUTHORS.rst
docs/index.rst

Added a brief summary to docs for users.
This documentation goes above the Contents.

Add brief summary to docs

---

AUTHORS.rst

Tagging @szuckerman and @zbarry as project leads.

Tagging @szuckerman and @zbarry as project leads.

---

AUTHORS.rst
docs/conf.py

1. [x ] PR in from a fork off your branch. Do not PR from <your_username>:master, but rather from <your_username>:<branch_name>.
2. [x ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.
- [ x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
- docs build
- Fixing the intersphinx plugin support for pandas …

Intersphinx pandas

---

AUTHORS.rst
janitor/functions.py
tests/functions/test_to_datetime.py

This PR resolves #188 .
- Make `pd.to_datetime` a chainable method
- Add tests
- @ericmjl

Add to_datetime wrapper and include test

---

examples/notebooks/overview.ipynb

This PR resolves #166 .
1. [ x] PR in from a fork off your branch. Do not PR from <your_username>:master, but rather from <your_username>:<branch_name>.
2. [x ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.
- [ x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
- docs build
- Add support for example notebooks to appear in sphinx documentation …

Add support for nbsphinx to docs

---

examples/notebooks/tidytuesday_2019-05-07.ipynb

This PR resolves #184 
- docs build
- Add an example notebook with tidytuesday dataset
- @ericmjl

add example notebook

---

janitor/functions.py
tests/functions/test_groupby_agg.py

This PR resolves #204
- An example of how you could think about addressing this problem.
- Added a simple test
- Note: I haven't replicated all the kwargs across `GroupBy` and `agg` because it may not be the way in you which you want things to work.
- @ericmjl

Add ability to groupby and agg, but chain it within the same dataframe

---

requirements.txt

This PR resolves #220. 
- docs build
- 
- 
- 
- @ericmjl

Add nbsphinx to requirements #220

---

.azure-pipelines/templates/run-tests.yml

add code style checks to tests

---

janitor/functions.py

This PR resolves #(59).
- docs build
- Updated functions to receive `columns_names` instead of `columns`, while being backwards compatible
- @ericmjl

Fix naming conventions in get_dupes() and encode_categorical()

---

docs/conf.py
nbconvert_config.py
tests/functions/test_convert_excel_date.py
tests/functions/test_to_datetime.py

fix example + black

---

nbconvert_config.py
tests/chemistry/test_maccs_keys_fingerprint.py
tests/chemistry/test_molecular_descriptors.py
tests/chemistry/test_morgan_fingerprint.py
tests/chemistry/test_smiles2mol.py
tests/functions/test_change_type.py

- docs build
- 
- 
- 
- @ericmjl

black formatting applied

---

README.rst

Adds binder link to README. Resolves #149.

added binder link

---

AUTHORS.rst
Makefile

This PR resolves #249 
- docs build
- Adding the `PHONY` section to the Makefile allows cleaner calls of the Make functions that we define throughout the document
- @ericmjl

Add PHONY section to root makefile

---

.azure-pipelines/templates/run-tests.yml

make testing pipeline run four different scripts to catch failures

---

README.rst

This PR resolves #183 .
- docs build
- 
- 
- 
- @ericmjl

Improved DAG documentation

---

janitor/functions.py

This PR resolves #218 
- docs build
- 
- 
- 
- @ericmjl

Replaced inplace everywhere appropriately

---

README.rst

- docs build
- 
- 
- 
- @ericmjl

Remove image from readme (doesn't render on github)

---

docs/index.rst
docs/installation.rst
docs/notebooks.rst
examples/notebooks/pyjanitor_intro.ipynb
examples/notebooks/tidytuesday_20190423.ipynb
tests/functions/test_bin_numeric.py
tests/functions/test_convert_unix_date.py
tests/functions/test_idempotent.py

This PR resolves #292.
- docs build
- In the documentation table of contents rename Example notebooks to Examples.
- Remove the contributing info from the notebook pyjanitor_intro.ipynb.
- Remove the bold from …

Update the documentation.

---

janitor/functions.py

This PR resolves #244 
- docs build
- 
- 
- 
- @ericmjl

Fix encode categorical docstring

---

examples/notebooks/bad_values.ipynb

- docs build
- Added TOC header to Replacing Bad Values notebook example. 
- 
- 
- @ericmjl

Added TOC header

---

janitor/functions.py
tests/functions/test_groupby_agg.py

This PR resolves #286
- docs build
- Optionally allowed user to pass either a string or a list of strings to determine groupby behavior
- Added unit test to ensure it works properly
- @ericmjl

Add in multi-index groupby_agg and accompanying unit tests

---

.github/pull_request_template.md

- Added some more contextual information requested.

[DOC] Update pull_request_template.md

---

.github/ISSUE_TEMPLATE/bug_report.md

- Adds a bug report template to the pyjanitor issue tracker templates.

[DOC] Create bug report template.

---

examples/notebooks/dirty_data.ipynb
examples/notebooks/tidytuesday_20190423.ipynb
janitor/functions.py
tests/functions/test_fill_empty.py
tests/functions/test_get_features_targets.py

- Update naming of arguments in rename_column(), get_features_targets()
- docs build
- @ericmjl

[ENH] Update naming conventions in rename_column(), get_features_targets()

---

AUTHORS.rst
janitor/functions.py
tests/functions/test_add_column.py

- 
- 
- 
**This PR resolves #(put issue number here, and remove parentheses).**
- docs build
If you are adding …

column_added

---

.github/ISSUE_TEMPLATE/new_proposed_feature.md
janitor/functions.py
tests/functions/test_select_columns.py
tests/functions/test_transform_column.py
tests/functions/test_transform_columns.py

- Update naming conventions in `round_to_fraction()` and `transform_columns()`
- Update naming conventions in `currency_column_to_numeric()` and `select_columns()`
- docs build
If you are adding code changes, please ensure …

[DOC] Update naming conventions in functions and issue template

---

.readthedocs.yml
examples/notebooks/normalize.ipynb
requirements-dev.txt

- Install `pyjanitor` and `jupyter_client` while building, to enable notebook building.

[DOC] Update infrastructure for readthedocs

---

janitor/chemistry.py
janitor/finance.py
janitor/functions.py

- Added/corrected parameters missing from some docstrings
- Corrected reference in `_clean_accounting_column` docstring to argument `type`, which is now `cleaning_style`
- docs build
If you are adding code changes, please …

[DOC] Update missing docstring parameters

---

janitor/chemistry.py

mypy was complaining.
No issue is fixed here.

[TST] Rename descriptors to descriptors_mapping in chemistry.py

---

.azure-pipelines/templates/run-tests.yml
environment-dev.yml
pytest.ini
requirements-dev.txt

- Add codecov to build pipeline
- Re-enable coverage reports when running pytest.
**This PR resolves #342.**

[TST] Add codecov to build pipeline

---

README.rst

Update Azure build status badge in README.rst
- Update build status badge to new Azure Pipelines
**This PR resolves #346 .**
- @ericmjl

[DOC] Update Azure build badge

---

janitor/biology.py
janitor/chemistry.py
janitor/finance.py
janitor/functions.py
janitor/utils.py

Added and revised type hinting, addressed variable naming issues, inserted subtle bugs, etc.
Also resolves: #339 
@ericmjl

[ENH] Mega-refactoring

---

janitor/functions.py
janitor/utils.py

Fighting the good fight to make `functions.py` less gigantic.
Resolves #344

[ENH] move utility functions to utils.py

---

janitor/functions.py
tests/functions/test_data_description.py

[ENH] Datadesc repr

---

janitor/functions.py
tests/functions/test_filter_date.py

- Update naming of arguments in filter_date()
- It seemed like it was fine to combine `start` and `start_date` after formatting etc.
- docs build
Please tag …

Update naming conventions for filter_date()

---

README.rst

[DOC] Fix README typo

---

janitor/functions.py
tests/functions/test_take_first.py

This PR is to add the function `take_first()` as an expression for `sort_values().drop_duplicates()`.

[ENH] Add take_first function

---

.azure-pipelines/templates/run-tests.yml
docs/reference/general_functions.rst
docs/reference/janitor.functions/janitor.currency_column_to_numeric.md
docs/reference/janitor.functions/janitor.drop_duplicate_columns.md
docs/reference/janitor.functions/janitor.filter_column_isin.md
docs/reference/janitor.functions/janitor.filter_date.md
docs/reference/janitor.functions/janitor.filter_on.md
docs/reference/janitor.functions/janitor.filter_string.md
docs/reference/janitor.functions/janitor.groupby_agg.md
docs/reference/janitor.functions/janitor.round_to_fraction.md
docs/reference/janitor.functions/janitor.select_columns.md
docs/reference/janitor.functions/janitor.take_first.md
docs/reference/janitor.functions/janitor.then.md
docs/reference/janitor.functions/janitor.to_datetime.md
tests/functions/test_take_first.py

- Added take_first from #363 and other functions not presently covered in the docs.

[DOC] Update general_functions with missing functions

---

.azure-pipelines/pipeline-master.yml

- Some experiments making Azure only build on PR, rather than on every push.

[INF] Azure update

---

janitor/io.py
tests/io/test_read_csvs.py

- Update naming of arguments in `read_csvs()`
- Accept string or iterable of strings as argument
- Move tests to `io` folder
- docs build
Please tag maintainers …

Update `read_csvs()` naming, argument and testing

---

janitor/chemistry.py

- Fixed code-block sphinx directive so that docs correctly render.

[DOC] code-block fix on chemistry.py

---

janitor/chemistry.py

- `molecular_descriptors` had a few wonky places with its docstring. This PR fixes them.

[DOC] docfix on molecular_descriptors

---

.azure-pipelines/pipeline-master.yml
.azure-pipelines/templates/release.yml

- This PR enables automatic releases of new versions of `pyjanitor` if there has been a version change.
- The version change must happen manually, but once that is done and a push is made, a release will automatically be built and uploaded to PyPI.
- Because of `conda-forge`'s bots, the uploaded PyPI release will also be built into a conda-forge package. 
This issue closes #361.

[INF] Auto release

---

docs/reference/general_functions.rst
janitor/functions.py
tests/functions/test_join_apply.py

- Implements the join_apply function as proposed in #372. 
- Adds tests as well.
- Finally, added the new function to the docs.

[ENH] Implementation of join_apply

---

.azure-pipelines/pipeline-master.yml

[INF] removed autorelease

---

AUTHORS.rst
examples/add_column.md

- 
- 
- 
**This PR resolves #(put issue number here, and remove parentheses).**
- docs build
If you are adding …

[DOC] added spaces between Example2 and Example3

---

AUTHORS.rst
docs/notebooks

- Fixed all user profile links. 
- Added links to contributions, aka pull requests submitted by the user.
- removed broken link for deleted contributor's account 
**This PR resolves #398 .**
- docs build
If you are adding documentation …

[DOC] update and add contributor and contribution links

---

AUTHORS.rst
examples/notebooks/tidytuesday_20190423.ipynb
janitor/biology.py
janitor/chemistry.py
janitor/finance.py
janitor/functions.py
janitor/utils.py
tests/biology/test_join_fasta.py
tests/finance/test_convert_currency.py
tests/functions/test_join_apply.py
tests/utils/test_clean_accounting_column.py
tests/utils/test_currency_column_to_numeric.py
tests/utils/test_import_message.py
tests/utils/test_replace_empty_string_with_none.py

Updated text as supplied in the issue.
Made note book changes and added to AUTHORS.rst
**This PR resolves #422 .**
- docs build
- @ericmjl

[DOC] Adds TidyTuesday explanation

---

AUTHORS.rst
docs/conf.py
janitor/functions.py

-  Explicitly indicate in the docstring of each dataframe method in `functions.py` whether the original dataframe is mutated or not.
**This PR resolves #435**
- docs build
If you are …

[DOC] Indicate mutation behavior in functions.py docstrings #435

---

janitor/finance.py

- Explicitly indicate in the docstring of each dataframe method in `finance.py` whether the original dataframe is mutated or not.
**This PR resolves #435**
- docs build
If you are …

[DOC] Indicate mutation behavior in finance.py docstrings #435

---

janitor/biology.py

- Explicitly indicate in the docstring of each dataframe method in biology.py whether the original dataframe is mutated or not.
**This PR resolves #435.**
- docs build
If you are …

[DOC] Indicate mutation behavior in biology.py docstrings #435

---

environment-dev.yml

- Sync up requiremnets-dev.txt with environment-dev.yml, providing flexibility for developers.
**This PR resolves #450.**
cc: @zbarry

[INF] #450 Sync up requirements-dev.txt with environment-dev.yml

---

janitor/functions.py
tests/functions/test_find_replace.py

From Issue #455.  find_replace() raises a ValueError when a Null value (np.nan, None, etc) is in the keys of the mapper.
**This PR resolves #455
- docs build
If you are adding …

[ENH, TST]: raise error when using find_replace() on null values

---

CONTRIBUTING.rst
Makefile

Contributes to addressing #347 
* Added `make install` target.
* Added corresponding contributing documentation
* Updated contributing documentation in other ways
@ericmjl

[ENH/DOC] More-automated installation process

---

docs/general_functions.rst
docs/reference/general_functions.rst

- `get_dupes()` and `get_features_targets()` is missing from `general_functions.rst` and thus is not rendering on the docs. I added them.
- `reset_index_inplace()` is missing as well but was asked to keep it out for now.
**This PR resolves #439.**
- docs build
If `make check` does not …

[DOC] Functions missing from docs #439

---

janitor/biology.py

- Added Functional usage example to `janitor.biology.join_fasta()`
- Added Method chaining example to `janitor.biology.join_fasta()`
- Add type hint for `column_name` as `str` to `janitor.biology.join_fasta()`
**This PR resolves #441 .**
- docs build
If `make check` does not work for …

[DOC] Standardized Biology Function DocStrings

---

docs/conf.py

- Modified `conf.py` such that `make html` builds properly on Windows systems and without Admin rights on Windows
**This PR resolves #464**
- docs build
If you are adding code …

[INF] Conf make html windows 464

---

environment-dev.yml

Updates channel order to give preference to conda-forge and adds make to the list of dependencies.
**This PR resolves #(467).**
1. [X] PR in from a fork off your branch. Do not PR from `cjmayers`:master, but rather from `cjmayers`:infastructure-#467
- docs build
- @ericmjl

[INF] Updates yml file to point to conda-forge first and adds make

---

.gitignore

[INF] add docs/notebooks to gitignore

---

AUTHORS.rst

- Add @sallyhong, need to find a way to recognize the effort you made to triage issues.
- Fix @gaworecki5's line.
- Minor tweak to wording on @asearfos' contribution.
**This PR resolves #473.**

[DOC] Rebuild AUTHORS.rst

---

AUTHORS.rst
janitor/functions.py
tests/functions/test_concatenate_columns.py

- Raises `JanitorError` in `concatenate_columns`
**This PR resolves a part of #354.**
- docs build
If you are adding …

[ENH] Raises JanitorError in concatenate_column

---

CHANGELOG.rst

This closes issue #489. As per title.

[DOC] started release notes for version 0.18.1 #489

---

AUTHORS.rst

[DOC] Added contributions that did not leave git trace #483

---

CHANGELOG.rst

Updates `changelog` with @rahosbach’s contribution to calculate inflation adjustment.

[DOC] add inflation adjustment to changelog

---

CHANGELOG.rst

As per title.
This does not close any issue.
I just re-structured the changelog a bit and added one line about @shandou's contribution.

[DOC] prettyfying changelog

---

.gitignore

[INF] add pip-wheel-metadata to gitignore

---

README.rst

[DOC] Link to contribution docs for tests

---

janitor/functions.py
tests/functions/test_deconcatenate_column.py

Addresses #524. However, does not resolve it.

[BUG] changed assertion statements in deconcatenate_columns to error statements

---

CHANGELOG.rst

As per title. No review necessary.

[INF] updated changelog with new release on deck

---

CHANGELOG.rst
examples/notebooks/bad_values.ipynb

- Updated `bad_values` doc to demonstrate use of `update_where` function for filtering bad data.
**This PR resolves #530 .**
- …

[DOC] Update bad_values doc, fixes #530

---

.gitignore
AUTHORS.rst
environment-dev.yml
janitor/spark/__init__.py
janitor/spark/backend.py
janitor/spark/functions.py
requirements-dev.txt
requirements.txt
tests/spark/functions/test_clean_names.py
tests/spark/functions/test_clean_names_spark.py

* Added pyspark backend at `janitor.spark.backend`. Using the same naming convention as `janitor`, i.e. `spark` instead of `pyspark`.
* Like `janitor` import `janitor.spark.functions` when importing `janitor.spark`.
* Added a `clean_names` function at `janitor.spark.functions`. Also demonstrate that we can reuse some functions in `janitor`.
**This PR addresses #504.**
- Do use some discretion here; if there …

[ENH] Pyjanitor for PySpark

---

AUTHORS.rst
CHANGELOG.rst
CONTRIBUTING.rst
Makefile
README.rst
docs/reference/index.rst
docs/reference/janitor.spark.functions/janitor.spark.clean_names.md
docs/reference/pyspark.rst
janitor/functions.py
janitor/spark/functions.py
janitor/utils.py
tests/conftest.py
tests/functions/test_clean_names.py
tests/spark/conftest.py
tests/spark/functions/test_clean_names_spark.py

- Added `clean_names` to pyspark. The function is identical except `preserve_original_columns`.
- Added documentations.
- Refactored change case in `clean_names` and `_strip_underscores_func` in `janitor.utils` so that the pyspark `clean_names` can share the same function.
- Added spark testing DataFrame so that it is similar to pandas testing DataFrame.
- Added ` --cov-report html` to `test` in `Makefile` so that the html report is generated automatically.
- Added `both` and `None` to `test_clean_names_strip_underscores`. The branch was not included in the test suite.
1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:master, but rather from …

[ENH] Add pyspark clean_names

---

CHANGELOG.rst
janitor/functions.py
janitor/io.py
setup.py
tests/functions/test_encode_categorical.py
tests/functions/test_label_encode.py

- Replace assertions with raise exceptions
- Many exceptions use `JanitorError` to tie to `pyjanitor`
**This PR resolves #354 .**
- pycodestyle …

[ENH] Convert assert statements to raise exceptions

---

AUTHORS.rst
CHANGELOG.rst
README.rst

- Adding link to the contribution section in README
**This PR resolves #403**
- docs build
Once done, …

[DOC] Update contribution section in Readme, fixes #403 

---

CHANGELOG.rst
README.rst

- Updated README with @TomAugspurger's code block suggestion in #548.
**This PR resolves #548.**
Note to maintainers:
- Docs have been built and I confirm they render correctly.

[DOC] Update with functional pandas API

---

CHANGELOG.rst
janitor/biology.py
janitor/chemistry.py
janitor/engineering.py
janitor/spark/backend.py
janitor/spark/functions.py
janitor/utils.py
tests/utils/test_import_message.py

- `import_message()` accepts information for conda and pip installs
- `import_message()` provides relevant install instructions for python distribution, or if at all possible
**This PR resolves #559 .**
To do a very quick check that everything is …

[INF] import_message accepts pip/conda install commands

---

CHANGELOG.rst
docs/reference/general_functions.rst
janitor/functions.py
tests/functions/test_count_cumulative_unique.py

- Added a new count_cumulative_unique() method to functions.py that keeps a running total of unique values in a given column.
- Added a new test module called test_count_cumulative_unique.py that provides test coverage for for the count_cumulative_unique() method.
- Updated the changelog.
- Ran all linting, styling, and unit tests; everything passes.
- Updated the docs to include a record of this new method.
**This PR resolves #515.**
3. [x] Add a line to `CHANGELOG.rst` under …

[ENH] count_cumulative_unique() method

---

CHANGELOG.rst
janitor/functions.py
tests/functions/test_shuffle.py

- Add a reset_index parameter to shuffle()
**This PR resolves #540**
- docs build
Once done, please …

[ENH] Add a reset_index boolean kwarg to shuffle(), fixes #540

---

CHANGELOG.rst

As per title.
No review necessary.

[INF] Prepping changelog for new release

---

.bumpversion.cfg
CHANGELOG.rst
janitor/__init__.py
setup.py

As per title. No review necessary.

[INF] Bump version for release #566

---

CHANGELOG.rst
requirements.txt
setup.py

-allow feature-specific requirements.txt. Such as for biology, specifically requires biopython.
**This PR resolves #299.**
- …

[INF] Make requirements.txt smaller #299

---

AUTHORS.rst
CHANGELOG.rst
janitor/functions.py
tests/functions/test_coalesce.py

- Updated functions.py to modify coalesce function (and docstring) to include delete_columns option
- added test case
- updated AUTHORS and CHANGELOG
**This PR resolves #561 **
To do a very quick check that everything is correct, follow these steps …

[ENH] Added delete_columns option to coalesce function

---

CHANGELOG.rst
docs/reference/janitor.spark.functions/janitor.spark.update_where.md
docs/reference/pyspark.rst
janitor/spark/functions.py
tests/spark/conftest.py
tests/spark/functions/test_clean_names_spark.py
tests/spark/functions/test_update_where_spark.py

- Add `update_where` to `janitor.spark`.
**This PR adds `update_where` as listed in #547.**
- docs …

[ENH] Pyspark update where

---

docs/reference/janitor.functions/janitor.count_cumulative_unique.md

- Add `count_cumulative_unique` missed in #563.
**This PR resolves #515.**
- docs build
Once done, …

[DOC] Add count_cumulative_unique doc

---

janitor/spark/functions.py
tests/spark/functions/test_clean_names_spark.py

- Fixed `janitor.spark` `import_message`. See #562.
- Also sneak in another change. Remove unused import in `tests/spark/functions/test_clean_names_spark.py`
**This PR resolves #559.**
To do a very quick check that everything is correct, follow …

[ENH] Fix janitor.spark import_message

---

janitor/functions.py
tests/functions/test_groupby_agg.py

Editing groupby_agg to handle DataFrames with multiple columns

---

AUTHORS.rst
CHANGELOG.rst
CONTRIBUTING.rst
janitor/functions.py

- Reviewed examples for typos in the functional syntax / method chaining syntax to ensure that functional calls included the `df` argument and method chaining calls did not. Resolves #591.
- Fixed a couple of missing commas and parentheses in example codes.
- Removed extraneous indicators like `...` (which indicated the possibility of further method chaining) to make the examples match one another more closely.
- Removed a nested set of square brackets `[` `]` from an example that seemed like an error.
**This PR resolves #591.**
2. [x] If you're …

[DOC]: Reviewed and edited functional syntax examples.

---

janitor/__init__.py
janitor/functions.py
janitor/math.py
tests/math/test_exp.py
tests/math/test_log.py
tests/math/test_logit.py
tests/math/test_normal_cdf.py
tests/math/test_probit.py
tests/math/test_sigmoid.py
tests/math/test_z_score.py
tests/utils/test_skiperror.py
tests/utils/test_skipna.py

[ENH] Add math module for chaining mathematical operations

---

CHANGELOG.rst
janitor/functions.py
janitor/utils.py

- Move #noqa: E501 comments from end of long urls in docstring to end of docstring
- Will prevent #noqa comments appearing in online docs
- hat tip to @bdice for solution!
**This PR resolves #555 .**
To do a very quick check that …

[DOC] Move #noqa comment to end of docstrings to avoid docs pollution

---

CHANGELOG.rst
docs/janitor.functions/janitor.unionize_dataframe_categories.md
janitor/functions.py
tests/functions/test_unionize_dataframe_categories.py

- add `unionize_dataframe_categories` & associated tests
**This PR resolves #580.**
- docs build
Once done, please check off the check-box …

[ENH] Update list of dataframes' categoricals 

---

AUTHORS.rst
CHANGELOG.rst

- Fixed misformatted contributions hyperlinks
- Add missing authors tags in Changelog
**This PR resolves #597 .**
- @ericmjl

[DOC] Fix contributions hyperlinks and authors tags

---

janitor/functions.py

- See #607 
-
-
**This PR resolves #(put issue number here, and remove parentheses).**
- docs …

[DOC] Functions.py non-string column names

---

CHANGELOG.rst
Makefile
pyproject.toml

- Changed the Makefile and pyproject to have linting/formatting avoid any env or venv directories, to make checking and linting take a reasonable amount of time.
**This PR resolves N/A **
To do a very quick check that everything is correct, …

[INF] Make Black and Pycodestyle avoid venvs

---

CHANGELOG.rst
janitor/chemistry.py
janitor/engineering.py
janitor/ml.py

- Changed the typing for most "column_name(s)" to Hashable rather than enforcing strings, to more closely match Pandas API, except for instances where this didn't make sense (e.g. convert_units, where the column name has a string unit value).  Done for every module but functions.py to make pull request a reasonable size
**This PR resolves #589 .**
3. [X] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the …

[DOC] Module non string columns

---

CHANGELOG.rst

- Update `CHANGELOG.rst` for version number change
- @ericmjl

[DOC] Update version in `CHANGELOG.rst`

---

.bumpversion.cfg
janitor/__init__.py
setup.py

This is a version bump release to get @zbarry’s xarray stuff out.

Bump version: 0.18.3 → 0.19.0

---

AUTHORS.rst
CHANGELOG.rst
janitor/functions.py

…r on defaults
- Made description for transform_column dest_column_name kwarg clearer for defaults
**This PR resolves #487 .**
- pycodestyle …

[DOC] Made transform_column dest_column_name kwarg clearer

---

CHANGELOG.rst
janitor/functions.py
janitor/utils.py
tests/utils/test_replace_empty_string_with_none.py

- Replace `apply()` in several functions with `pandas` functions:
- `currency_column_to_numeric()`
- `round_to_fraction()`
- `filter_date()`
- `convert_unix_date()`
**This PR resolves #274 .**
To do a very quick check that everything is …

[ENH] Replace `apply()` with `pandas` functions

---

CHANGELOG.rst
janitor/functions.py
janitor/math.py
janitor/xarray/functions.py
tests/math/test_ecdf.py
tests/xarray/conftest.py
tests/xarray/test_clone_using.py
tests/xarray/test_convert_datetime_to_number.py

[ENH] Add ECDF function

---

CHANGELOG.rst
README.rst

[DOC] Added API policy to the README

---

CHANGELOG.rst
docs/reference/general_functions.rst
docs/reference/janitor.functions/janitor.jitter.md
janitor/functions.py
janitor/xarray/functions.py
tests/functions/test_jitter.py
tests/xarray/conftest.py
tests/xarray/test_clone_using.py
tests/xarray/test_convert_datetime_to_number.py

- Added jitter() method to functions.py.
- Added related tests in test_jitter.py.
- Updated docs in general_functions.rst.
- Updated CHANGELOG.rst.
- Linting and Black formatting updated some other xarray modules as well (not sure why that is, but they are included here).
**This PR resolves #622.**
- Do use some discretion here; if there are …

[ENH] Issue 622: Jitter Method

---

AUTHORS.rst
CHANGELOG.rst
examples/notebooks/groupby_agg.ipynb

- Added an example for groupby_agg in general functions
-
-
**This PR is for #187 **
- docs …

[DOC]: Added an example for groupby_agg in general functions

---

.bumpversion.cfg
janitor/__init__.py
setup.py

- Bump the version
**This PR resolves #632.**

[DOC] Bump version: 0.19.0 -> 0.20.0 (#632)

---

.bumpversion.cfg
janitor/__init__.py
requirements.txt
setup.py

[PATCH] Patch natsort

---

AUTHORS.rst
CHANGELOG.rst
janitor/functions.py
tests/functions/test_select_columns.py

- `.select_columns()` will now raise `NameError` if column labels in `search_column_labels` are note found in `df.columns`.
**This PR resolves #647**
- black …

[ENH] .select_columns() raises NameError when passed missing column labels

---

tests/xarray/test_clone_using.py

I recently installed deepsource as another code checker. It's premised on some pretty cool stuff, including what I think is a deep neural network of some kind.
In any case, I'm going to go through and slowly fix up code problems that it detects.

Fixes based on deepsource

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
CONTRIBUTING.rst

In this PR, I'm adding docs for how to use dev containers.

Dev container docs

---

janitor/functions.py
tests/finance/test_convert_currency.py
tests/finance/test_inflate_currency.py

- Adds docstrings to tests in following modules:
- `finance`
- Fixes some typos throughout project
I did not write any of the original functions or tests, and am open to feedback for better descriptions.
**This PR partially addresses #306.**
- Do use some discretion here; if there are multiple PRs that are related, keep them in a single …

[TST] Add docstrings for inflate_currency tests

---

examples/notebooks/expand_grid.ipynb
janitor/functions.py
janitor/utils.py

- Example notebook added for the expand_grid function.
- Speed improvement on the expand_grid function
-
**This PR - Request Changes for the expand_grid function.**
To do a very quick check that everything is correct, follow these steps …

[DOC][ENH] updates to expand_grid; example notebook included

---

CHANGELOG.rst
environment-dev.yml
requirements.txt

- Updates minimum `pandas` version from 0.24 to 1.0.0
**This PR does not directly resolve an issue, but arose from conversation with @ericmjl.**
**Our CI uses the latest version of `pandas`, and this simplifies (likely) future compatibility issues.**
As some background, this initially arose because we have some tests that import from `pandas._testing`, which doesn't exist <1.0. I think we should import from `pandas.testing` anyway, so the `pandas` version becomes less of an issue. However, if we're claiming to be `pandas>=0.24` compatible, we might want to consider adding a CI job that will test on `pandas==0.24` in addition to `pandas==latest`.
1. [X] PR in from a fork off your …

[INF] Require pandas >= 1.0.0

---

CHANGELOG.rst
docs/reference/general_functions.rst

- Added functions to the general_functions API page
-
-
**This PR resolves #678 .**
- flake8 checking
- docs build …

[DOC] Updated general_functions API page

---

scripts/check-autodoc.py

Fix typo in `skipcq` to ignore issues on DeepSource
Since there are no code changes, I am skipping the other items on the checklist. 
1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.
- flake8 checking
- docs build
Once done, …

[ENH] Fix typo in skipcq

---

CHANGELOG.rst
docs/reference/general_functions.rst
tests/functions/test_expand_grid.py

- This is a test update in reference to #675 
-
**This PR refers to #675.**
1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.
- flake8 checking
- docs build
Once done, …

[TST] Fix expand_grid test on Windows

---

CHANGELOG.rst
tests/functions/test_add_column.py
tests/functions/test_add_columns.py
tests/functions/test_collapse_levels.py
tests/functions/test_deconcatenate_column.py
tests/functions/test_dropnotnull.py
tests/functions/test_expand_grid.py
tests/functions/test_join_apply.py
tests/functions/test_select_columns.py
tests/functions/test_sort_naturally.py
tests/functions/test_take_first.py
tests/functions/test_transform_column.py
tests/functions/test_transform_columns.py
tests/functions/test_unionize_dataframe_categories.py
tests/functions/test_update_where.py
tests/spark/functions/test_update_where_spark.py
tests/utils/test_replace_empty_string_with_none.py

- This imports `assert_frame_equal` directly from `pandas.testing` instead of using `pd.testing.assert_frame_equal`
- Also changes imports from private `pandas._testing` to `pandas.testing`
**This PR resolves #674.**
To do a very quick …

[TST] Import `pandas` test functions in uniform pattern

---

CHANGELOG.rst
CONTRIBUTING.rst
docs/CONTRIBUTION_TYPES.rst

- Fixes display of numbered list in Docker setup instructions
- Applies some recommendations from MS Word
- Applies more semantic line breaks to docs
**This PR has no corresponding issue.**
To do a very quick check that everything is …

[DOC] Fix minor documentation formatting and grammar
